version: 2.1

jobs:
  build:
    working_directory: ~/docker
    docker:
      - image: docker:stable

    steps:
      - run:
          name: nop
          command: echo Hei

  update_version:
    working_directory: ~/docker
    docker:
      - image: alpine
    
    steps:
      - run:
          name: Install packages
          command: apk --update --no-cache add bash git curl openssh-client jq
      
      - checkout

      - run:
          name: Update git profiles
          command: |
            git config push.default current
            git config user.name "CircleCI bot"
            git config user.email ${EMAIL}

      - run:
          name: Check emscripten version and update
          command: bash docker/UpdateEmscripten.sh

workflows:
  version: 2

  build:
    jobs:
      - build

  daily_update:
    triggers:
      - schedule:
          # START UTC 21:00(JST 6:00)
          cron: "0 21 * * *"
          filters:
            branches:
              only: master
    jobs:
      - update_version
